import type { Seed } from '../src/seeds/types';

export const seed001Core: Seed = {
  id: '001_core',
  description: 'Seed base quests',
  async run({ knex }) {
    const questSeeds = [
      {
        title: 'Merge a PR',
        description: 'Get a pull request merged into main',
        target_count: 1,
        xp_reward: 20,
        subject_type: 'user',
      },
      {
        title: 'Review PRs',
        description: 'Leave meaningful reviews (XP every 3)',
        target_count: 3,
        xp_reward: 15,
        subject_type: 'user',
      },
      {
        title: 'Fix a failing build',
        description: 'Make CI green again (XP every 2)',
        target_count: 2,
        xp_reward: 30,
        subject_type: 'user',
      },
      {
        title: 'Close Stale Issues',
        description: 'Triage and close outdated GitHub issues',
        target_count: 5,
        xp_reward: 25,
        subject_type: 'user',
      },
      {
        title: 'Write Release Notes',
        description: 'Publish release notes for a completed sprint',
        target_count: 1,
        xp_reward: 35,
        subject_type: 'user',
      },
      {
        title: 'Document a Service',
        description: 'Improve service documentation in Backstage',
        target_count: 2,
        xp_reward: 30,
        subject_type: 'user',
      },
      {
        title: 'Resolve Dependency Alerts',
        description: 'Handle dependency and security upgrade alerts',
        target_count: 4,
        xp_reward: 40,
        subject_type: 'user',
      },
      {
        title: 'Help Onboard a Teammate',
        description: 'Pair with a new teammate on their first contribution',
        target_count: 1,
        xp_reward: 25,
        subject_type: 'user',
      },
      {
        title: 'Increase Test Coverage',
        description: 'Add or improve automated tests in a code area',
        target_count: 3,
        xp_reward: 45,
        subject_type: 'user',
      },
      {
        title: 'Refactor a Workflow',
        description: 'Simplify a CI/CD or engineering workflow',
        target_count: 2,
        xp_reward: 35,
        subject_type: 'user',
      },
      {
        title: 'Ship Your First Feature Flag',
        description: 'Launch your first feature flag safely to production',
        target_count: 1,
        xp_reward: 50,
        subject_type: 'user',
        completion_policy: 'ONE_TIME',
      },
      {
        title: 'Lead a Production Rollout',
        description: 'Own a full production rollout from start to finish',
        target_count: 1,
        xp_reward: 60,
        subject_type: 'user',
        completion_policy: 'ONE_TIME',
      },
      {
        title: 'Run a Knowledge Share',
        description: 'Host a team knowledge-sharing session',
        target_count: 1,
        xp_reward: 40,
        subject_type: 'user',
        completion_policy: 'ONE_TIME',
      },
      {
        title: 'Dependency Hygiene Sprint',
        description: 'Keep team-owned repositories on supported dependencies',
        target_count: 2,
        xp_reward: 60,
        subject_type: 'team',
      },
      {
        title: 'Security Patch Sweep',
        description:
          'Apply critical dependency and container patches as a team',
        target_count: 1,
        xp_reward: 80,
        subject_type: 'team',
        completion_policy: 'ONE_TIME',
      },
      {
        title: 'Shared Release Readiness',
        description: 'Coordinate final checks before a release together',
        target_count: 3,
        xp_reward: 90,
        subject_type: 'team',
      },
      {
        title: 'Incident Follow-up',
        description: 'Complete post-incident actions as a team',
        target_count: 1,
        xp_reward: 70,
        subject_type: 'team',
      },
      {
        title: 'Documentation Drive',
        description: 'Improve docs across a team-owned service area',
        target_count: 5,
        xp_reward: 55,
        subject_type: 'team',
      },
      {
        title: 'Platform Cleanup Week',
        description: 'Reduce backlog and maintenance debt together',
        target_count: 4,
        xp_reward: 65,
        subject_type: 'team',
      },
      {
        title: 'Accessibility Audit',
        description: 'Review and fix accessibility issues as a team',
        target_count: 2,
        xp_reward: 50,
        subject_type: 'team',
        completion_policy: 'REPEATABLE',
        cooldown_days: 14,
      },
    ].map(quest => ({
      completion_policy: 'REPEATABLE' as const,
      cooldown_days: null as number | null,
      ...quest,
    }));

    await knex('quests').insert(questSeeds).onConflict('title').ignore();
  },
};
