apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: our-backstage
  description: Local Backstage instance for developing and testing internal plugins (including gamification).
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: BTH-Trafikverket/our-backstage
spec:
  type: website
  owner: user:default/LinusAndersson02
  lifecycle: experimental
  consumesApis:
    - api:default/gamification-api
