apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
  namespace: local
spec:
  profile:
    displayName: Alice Example
    email: alice@example.com
  memberOf:
    - group:default/admin
